# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/Users/Amanjit/Desktop/Camera/project_1/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/Amanjit/Desktop/Camera/project_1/project_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/Users/Amanjit/Desktop/Camera/project_1/project_1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/Amanjit/Desktop/Camera/project_1/project_1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/I2C_OV7670_RGB444_Config.v
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/I2C_Controller.v
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/vga444.v
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/ov7670_capture.v
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/I2C_AV_Config.v
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/debounce.v
  C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/sources_1/imports/src/ov7670_top.v
}
read_xdc C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/constrs_1/imports/src/nexys4_ov7670.xdc
set_property used_in_implementation false [get_files C:/Users/Amanjit/Desktop/Camera/project_1/project_1.srcs/constrs_1/imports/src/nexys4_ov7670.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Amanjit/Desktop/Camera/project_1/project_1.cache/wt [current_project]
set_property parent.project_dir C:/Users/Amanjit/Desktop/Camera/project_1 [current_project]
synth_design -top ov7670_top -part xc7a100tcsg324-1
write_checkpoint ov7670_top.dcp
report_utilization -file ov7670_top_utilization_synth.rpt -pb ov7670_top_utilization_synth.pb
